{% set version = "1.6-1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nada
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/NADA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/NADA/NADA_{{ version }}.tar.gz
  sha256: 837dc66bc880285985ce1c0da9897f437207fad6ec69c3f0879fbaf4a4ace2b4

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-survival
  run:
    - r-base
    - r-survival

test:
  commands:
    - $R -e "library('NADA')"           # [not win]
    - "\"%R%\" -e \"library('NADA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=NADA
  license: GPL-2.0-or-later
  summary: 'Contains methods described by Dennis Helsel in his book "Nondetects And Data Analysis: Statistics for Censored Environmental Data".'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: NADA
# Title: Nondetects and Data Analysis for Environmental Data
# Version: 1.6-1.1
# Author: Lopaka Lee
# Description: Contains methods described by Dennis Helsel in his book "Nondetects And Data Analysis: Statistics for Censored Environmental Data".
# Maintainer: Lopaka Lee <rclee@usgs.gov>
# Depends: R (>= 2.10), methods, survival
# License: GPL (>= 2)
# Collate: All.R summary.R cen.R km.R reg.R mle.R ken.R ros.R icmle.R
# Packaged: 2020-03-22 09:25:45 UTC; hornik
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2020-03-22 09:46:09 UTC
