travis:
  secure:
    BINSTAR_TOKEN: RlQtb4VoQSnKTRLiYeyaQKip85TTrDHyiodXB9BX14Z+9fNA+V3797UXtLtQcvW7iIkgMw0/0+ZCOWQzkci7xJv8zHquifRElURzdXuzdTPQ0JDdJ+yhUVnKfupzrFgD+ZUAwSI5VXUnfuc3FCq//LPOJDUiGJ96F6CiOmq3LfV85B7znRMPuAebBkd/Q19pKRlKlSwuFmxAhoWtO+cx/14s+0UOvUDIosB6/8T2t5biBkYO8CD3drgV4N30vrp1dngU08+Vp3vA3KulN+dAuW8BYcnuwQSsT0P7+ZxQZsJpy5qV8Gomx/4FvGfqi8wSV1dPdcUzSHz7aY4js6/jODWpjiPeje63qity/2gFqe24cS9XCGqa64Trb3F/AjgLwpBKfxVFOymeIVrIBbYvrU48cHGcXKQ5idnqSKm4s0HOH1tEyBj5J5IPcrNFap2j20q+8imdnZP/fFPKcr48loPPe7tubhxQ5QWGrcDaFfujn53R/irJtEdcFojz5xq2njbfm2oAhBWWRgakpKIWhErDFdV0Ld0PyU5uCVYEIXpQ3f4HMCrMXmp0wM7KS1fPDBzAp4UeOE1fOYlrU3yg823crw0HJXFMKF5l8H1E8E1ow+BwdqOgj0NKegtnN8LiUK0YOjWXZVsM02eAAl0clSwadCQ0e4E6sOdmfrKg9ME=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
